fixed testing for an inconsistent requirement
was causing: 
[echo] (BUG) Price of Aged Parmesan increases one unit everyday even after sell in day
[echo]  expected:<51> but was:<50>